import fs from "node:fs";
import path from "node:path";
import { clerk, setupClerkTestingToken } from "@clerk/testing/playwright";
import type {
	APIRequestContext,
	Browser,
	BrowserContext,
	Page,
} from "@playwright/test";

export type UserContext = {
	context: BrowserContext;
	page: Page;
	request: APIRequestContext;
};

/**
 * Test user credentials — must match users created via scripts/setup-test-users.ts
 */
const TEST_USERS: Record<string, { email: string; password: string }> = {
	ada: {
		email: "ada-test@cushlabs.ai",
		password: "AdaTestPw2026!",
	},
	babbage: {
		email: "babbage-test@cushlabs.ai",
		password: "BabbageTestPw2026!",
	},
	curie: {
		email: "curie-test@cushlabs.ai",
		password: "CurieTestPw2026!",
	},
};

/**
 * Creates an authenticated browser context for Playwright tests.
 *
 * Uses @clerk/testing/playwright to:
 * 1. Inject the testing token (bypasses bot detection)
 * 2. Sign in with real test user credentials via Clerk API
 *
 * Requires CLERK_TESTING_TOKEN env var (generated by clerkSetup() or CI workflow).
 */
export async function createAuthenticatedContext({
	browser,
	name,
}: {
	browser: Browser;
	name: string;
}): Promise<UserContext> {
	const directory = path.join(__dirname, "../playwright/.sessions");

	if (!fs.existsSync(directory)) {
		fs.mkdirSync(directory, { recursive: true });
	}

	// Extract the base user name (e.g., "ada" from "ada-0-1771894200")
	const baseName = name.split("-")[0];
	const user = TEST_USERS[baseName];
	const storageFile = path.join(directory, `${name}.json`);

	const context = await browser.newContext();
	const page = await context.newPage();

	if (!user) {
		console.warn(
			`No test credentials for "${baseName}". Creating unauthenticated context.`,
		);
		return { context, page, request: context.request };
	}

	try {
		console.log(`[auth] Setting up testing token for "${baseName}"...`);

		// Inject the Clerk testing token to bypass bot detection
		await setupClerkTestingToken({ page });

		console.log(`[auth] Navigating to "/" for "${baseName}"...`);

		// Navigate to a page that loads Clerk before signing in
		await page.goto("/", { waitUntil: "networkidle" });

		console.log(
			`[auth] Page loaded at ${page.url()}, signing in as "${baseName}"...`,
		);

		// Sign in using Clerk's testing helpers (calls Clerk API directly, no UI interaction)
		await clerk.signIn({
			page,
			signInParams: {
				strategy: "password",
				identifier: user.email,
				password: user.password,
			},
		});

		console.log(`[auth] clerk.signIn() completed for "${baseName}"`);

		// Verify authentication by navigating to a protected route
		await page.goto("/chat", { waitUntil: "networkidle", timeout: 30000 });
		const finalUrl = page.url();

		if (finalUrl.includes("/sign-in") || finalUrl.includes("/sign-up")) {
			throw new Error(
				`Authentication verification failed for "${baseName}". ` +
					`Expected /chat but landed on ${finalUrl}. ` +
					"The sign-in completed but session was not established.",
			);
		}

		console.log(
			`[auth] Verified: "${baseName}" authenticated (landed on ${finalUrl})`,
		);

		// Save session state for potential reuse
		await context.storageState({ path: storageFile });
	} catch (error) {
		console.error(
			`[auth] Failed to authenticate "${baseName}" (${user.email}). ` +
				"Ensure test users exist in Clerk — run: pnpm test:setup\n",
			error,
		);
		throw error;
	}

	return { context, page, request: context.request };
}
